version: '3.1'

services:

  postgres-deduplication:
    build:
      context: .
      dockerfile: postgres.dockerfile
#    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/postgres